spring.application.name=task-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.hiddenmethod.filter.enabled=true

jwt.secretKey = sdkfjjshgfdaoisuydoiwaeufksldjhflksjhfkljhfkasjdhfioauweysjnflsaudyfsiouvih

#spring.sql.init.schema-locations=file:/home/sriram-nangunoori/Documents/Task_Manager/task-manager/src/main/resources/schema.sql