spring.application.name=task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db

# These pull dynamically from the system!
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secretKey=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

admin.default.password=${ADMIN_PASS}
