spring.application.name=task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.mvc.hiddenmethod.filter.enabled=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secretKey=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update
admin.default.password=${ADMIN_PASS}

spring.data.redis.password=${REDIS_PASSWORD}
